/**
 * backfill-queue.ts — drain the drive_sync_runs queue once.
 *
 * Invoked by the `backfill-pending` mode of main.ts. Mirrors the canonical
 * pattern-A job-runner shape from gub-research-worker (the reference
 * implementation; see project_standalone_job_pattern.md "Enqueue is the
 * trigger" — no Cloud Scheduler).
 *
 * Lifecycle of one Job execution:
 *   1. reclaimStaleRunning() — reset orphaned `running` rows (the previous
 *      Job process died mid-call) back to `pending`. Self-heal, no scheduler.
 *   2. drainQueue() — single serial worker (LLM-bound, parallel makes
 *      cost/latency worse, not better). Loops claim → process → claim
 *      until claimNext() returns null. Then exits.
 *
 * Concurrency: claimNext() uses raw-SQL SELECT … FOR UPDATE SKIP LOCKED
 * inside a Prisma $transaction — the canonical pattern. Lets multiple Job
 * executions race safely if Cloud Run ever overlaps them (single-
 * execution-at-a-time is the operational expectation, but the safety net
 * costs nothing).
 *
 * Retry policy: a row that errors during processing is re-queued with
 * exponential backoff (60s → 120s → 240s, capped at 30min) and stays
 * eligible for the next claim cycle WITHIN THIS Job execution OR a future
 * one. After MAX_ATTEMPTS the row is marked terminal-failed; the operator
 * resolves it through the UI (re-queue or investigate). No periodic retry
 * infra — a human is in the loop for permanent failures.
 *
 * Trigger model: this is invoked by `triggerDriveSyncJob({ mode:
 * 'backfill-pending' })` in gub-admin's POST handler when the operator
 * clicks Backfill. There is no Cloud Scheduler — enqueue-as-trigger per
 * the locked Pattern A design.
 */

import { GoogleAuth } from 'google-auth-library';
import { config } from '../config';
import { prisma } from '../prisma';
import { summarizeError } from '../progress';
import { runBackfill } from '../backfill';
import { runForward } from '../forward/run';

/** Stale-running recovery threshold — see project_drive_sync_architecture.md "Self-healing reapers". */
/**
 * Reclaim threshold = 3× heartbeat interval. The engine writes a
 * heartbeat every HEARTBEAT_INTERVAL_MS during a scan; three missed
 * cycles → almost certainly dead (network blip, GC pause, slow LLM
 * call can each eat 1 cycle; 3 in a row is the crash signal).
 *
 * Was 60 min (started_at-based), missed OOM crashes mid-scan because
 * started_at is set once at claim and never updated — a row claimed
 * 40 min ago looked identical whether the engine was humming along or
 * SIGKILL'd at minute 30. Now it's heartbeat-derived liveness.
 */
const STALE_RUNNING_MS = 15 * 60 * 1_000; // 15 minutes
const HEARTBEAT_INTERVAL_MS = 5 * 60 * 1_000; // 5 minutes
/** Per-invocation drain safety cap. Backstop so a runaway queue can't extend a single Job execution indefinitely. */
const MAX_REQUESTS_PER_INVOCATION = 50;
/** Maximum claim count before a row is marked terminal-failed. Mirrors gub-research-worker. */
const MAX_ATTEMPTS = 3;
/** Exponential backoff base: 60s → 120s → 240s, capped at BACKOFF_MAX_MS. */
const BACKOFF_BASE_MS = 60 * 1_000;
const BACKOFF_MAX_MS = 30 * 60 * 1_000;
const LOG_SUMMARY_TAIL_LINES = 40;
const LOG_SUMMARY_MAX_BYTES = 2_000;
/**
 * DRIVE_SYNC_SYSTEM_STAFF_ID — seeded by migration 20260525100000.
 * Continuation requests are auto-generated by the engine, not a real
 * operator click; we attribute them to this system identity so the
 * audit trail is clear and there's no FK back to a human staff row.
 */
const DRIVE_SYNC_SYSTEM_STAFF_ID = 'dcd5d8e3-0000-4000-a000-000000000001';

export interface ProcessBackfillQueueResult {
  reclaimed: number;
  processed: number;
  completed: number;
  failed: number;
  retriedLater: number;
  hitMaxRequests: boolean;
}

function tailLogSummary(capture: string[]): string {
  const tail = capture.slice(-LOG_SUMMARY_TAIL_LINES).join('\n');
  if (tail.length <= LOG_SUMMARY_MAX_BYTES) return tail;
  return '…\n' + tail.slice(tail.length - LOG_SUMMARY_MAX_BYTES);
}

function backoffMs(attempts: number): number {
  // attempts=1 (just claimed first time) → 60s
  // attempts=2 → 120s
  // attempts=3 → 240s
  const exp = BACKOFF_BASE_MS * Math.pow(2, Math.max(0, attempts - 1));
  return Math.min(exp, BACKOFF_MAX_MS);
}

/**
 * Reset `running` rows whose liveness pulse is older than STALE_RUNNING_MS
 * back to `pending`. Runs once at the start of every Job execution.
 *
 * Uses last_heartbeat_at as the primary liveness signal; falls back to
 * started_at for rows from before the heartbeat column existed (NULL).
 * Heartbeat is written on claim + every HEARTBEAT_INTERVAL_MS while the
 * scan runs, so missing it for STALE_RUNNING_MS (3× interval) means
 * the worker is almost certainly dead (OOM SIGKILL, container restart,
 * network partition that closed the DB connection, etc.).
 *
 * Mirrors gub-research-worker's reclaimStaleRunning — name kept identical
 * for cross-repo grep-ability.
 */
async function reclaimStaleRunning(): Promise<number> {
  const cutoff = new Date(Date.now() - STALE_RUNNING_MS);
  const res = await prisma.driveSyncRun.updateMany({
    where: {
      status: 'running',
      OR: [
        { lastHeartbeatAt: { lt: cutoff } },
        // Legacy rows pre-heartbeat — fall back to started_at so we don't
        // either reclaim healthy in-flight pre-deploy rows OR leave them
        // running forever. After all pre-deploy rows terminate this OR
        // branch goes cold; can drop later.
        { lastHeartbeatAt: null, startedAt: { lt: cutoff } },
      ],
    },
    data: {
      status: 'pending',
      errorMessage: 'reclaimed: stale running (heartbeat missed — worker died)',
    },
  });
  return res.count;
}

/**
 * Claim the next eligible row atomically. Raw-SQL SELECT … FOR UPDATE
 * SKIP LOCKED inside a Prisma $transaction — the canonical pattern
 * (`project_standalone_job_pattern.md`, mirrored from gub-research-worker
 * src/job-runner.ts). Prisma doesn't expose SKIP LOCKED in its query API.
 *
 * Increments `attempts` and stamps `started_at` as part of the claim
 * transaction — the row is in `running` state when the function returns.
 */
async function claimNext(): Promise<{
  id: string;
  accountId: string;
  mode: string;
  attempts: number;
  allRemaining: boolean;
} | null> {
  return prisma.$transaction(async (tx) => {
    const rows = await tx.$queryRaw<Array<{ id: string }>>`
      SELECT id FROM drive_sync_runs
      WHERE status = 'pending'
        AND (next_attempt_at IS NULL OR next_attempt_at <= NOW())
      ORDER BY requested_at
      LIMIT 1
      FOR UPDATE SKIP LOCKED
    `;
    if (rows.length === 0) return null;
    const jobId = rows[0]!.id;
    return tx.driveSyncRun.update({
      where: { id: jobId },
      data: {
        status: 'running',
        startedAt: new Date(),
        // Initial heartbeat stamp at claim time. The 5-min ticker in
        // processOne keeps it fresh; without this seed, a row that
        // claimed but crashed BEFORE the first tick would have null
        // heartbeat and fall through to the startedAt-fallback branch
        // in reclaimStaleRunning — works, but the heartbeat path is
        // the intended primary.
        lastHeartbeatAt: new Date(),
        attempts: { increment: 1 },
      },
      select: {
        id: true,
        accountId: true,
        mode: true,
        attempts: true,
        allRemaining: true,
      },
    });
  });
}

/**
 * Write a continuation request and self-trigger a fresh Job execution
 * via Cloud Run Admin API. Mirrors drive.runner.ts:scheduleContinuation —
 * same Admin API call, same auth (runtime SA + ADC), same `jobs:run`
 * with containerOverrides.args = ['backfill-pending'].
 *
 * The continuation request:
 *   - inherits accountId + allRemaining=true from the truncated parent
 *   - requested_by = DRIVE_SYNC_SYSTEM_STAFF_ID (engine-generated, not human)
 *   - log_summary references the parent's id for audit trail
 *
 * Fire-and-don't-wait: we await the Admin API response (to know the
 * trigger landed) but we don't wait for the new execution to start
 * processing. If the trigger fails the continuation request stays
 * `pending` for the next manual click or scheduled invocation to pick up.
 */
type ContinuationOutcome = 'triggered' | 'row_write_failed' | 'trigger_failed' | 'misconfig';

async function scheduleContinuation(
  parentRequestId: string,
  accountId: string,
  mode: string,
): Promise<ContinuationOutcome> {
  const project = config.GCP_PROJECT_ID;
  const region = config.GCP_REGION;
  const job = config.DRIVE_SYNC_JOB_NAME;
  if (!project || !region || !job) {
    console.error(
      JSON.stringify({
        msg: 'backfill-queue.continuation.misconfig',
        parentRequestId,
        project: !!project,
        region: !!region,
        job: !!job,
        hint: 'GCP_PROJECT_ID / GCP_REGION / DRIVE_SYNC_JOB_NAME must be set',
      }),
    );
    return 'misconfig';
  }

  // Write the continuation request first. If the Admin API trigger
  // fails, this row sits pending and will be picked up by the next
  // manual click or invocation — the failure is recoverable.
  let continuationId: string;
  try {
    const created = await prisma.driveSyncRun.create({
      data: {
        accountId,
        mode,
        allRemaining: true,
        requestedBy: DRIVE_SYNC_SYSTEM_STAFF_ID,
        logSummary: `auto-continuation of ${parentRequestId}`,
      },
      select: { id: true },
    });
    continuationId = created.id;
  } catch (err) {
    console.error(
      JSON.stringify({
        msg: 'backfill-queue.continuation.write_failed',
        parentRequestId,
        error: err instanceof Error ? err.message : String(err),
      }),
    );
    return 'row_write_failed';
  }

  const url =
    `https://run.googleapis.com/v2/projects/${project}` +
    `/locations/${region}/jobs/${job}:run`;
  const body = {
    overrides: {
      containerOverrides: [
        {
          args: ['backfill-pending'],
        },
      ],
    },
  };

  try {
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform'],
    });
    const client = await auth.getClient();
    await client.request({
      url,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: body,
    });
    console.log(
      JSON.stringify({
        msg: 'backfill-queue.continuation.triggered',
        parentRequestId,
        continuationId,
        job,
      }),
    );
    return 'triggered';
  } catch (err) {
    console.error(
      JSON.stringify({
        msg: 'backfill-queue.continuation.trigger_failed',
        parentRequestId,
        continuationId,
        error: err instanceof Error ? err.message : String(err),
        hint: 'continuation row stays pending; the still-warm drain loop or the next manual click picks it up',
      }),
    );
    return 'trigger_failed';
  }
}

type ProcessOutcome =
  | {
      kind: 'completed';
      /**
       * True when processOne fired scheduleContinuation (the chunk hit
       * its wall-clock budget and a new Job execution was triggered).
       * The drain loop checks this and exits — continuing to claim
       * rows in the current Job after triggering a successor races us
       * to grab the continuation row we just wrote.
       */
      continuationFired: boolean;
    }
  | { kind: 'retried' }
  | { kind: 'failed' };

async function processOne(req: {
  id: string;
  accountId: string;
  mode: string;
  attempts: number;
  allRemaining: boolean;
}): Promise<ProcessOutcome> {
  console.log(
    JSON.stringify({
      msg: 'backfill-queue.processing',
      requestId: req.id,
      accountId: req.accountId,
      mode: req.mode,
      attempts: req.attempts,
      allRemaining: req.allRemaining,
    }),
  );

  // Heartbeat ticker — bumps last_heartbeat_at every HEARTBEAT_INTERVAL_MS.
  // reclaimStaleRunning treats absence-of-heartbeat (>STALE_RUNNING_MS old)
  // as crash; this keeps the row alive in the DB's eyes. Errors are swallowed
  // (best-effort) so a transient DB blip doesn't kill the running scan. The
  // initial heartbeat was already stamped by claimNext at row claim time.
  const heartbeat = setInterval(() => {
    prisma.driveSyncRun
      .update({
        where: { id: req.id },
        data: { lastHeartbeatAt: new Date() },
      })
      .catch((err) => {
        console.warn(
          JSON.stringify({
            msg: 'backfill-queue.heartbeat_failed',
            requestId: req.id,
            error: err instanceof Error ? err.message : String(err),
          }),
        );
      });
  }, HEARTBEAT_INTERVAL_MS);

  const captureLog: string[] = [];
  try {
    // Driver dispatch: bootstrap rows day-walk history (auto-apply);
    // forward rows drain the Activity window (propose for review).
    const result =
      req.mode === 'forward'
        ? await runForward({ accountId: req.accountId, captureLog })
        : await runBackfill({
            accountId: req.accountId,
            newestFirst: false,
            outputPath: null,
            structureOnly: false,
            dryrun: false,
            captureLog,
          });
    // Bookkeeping persist gets its own guard: the scan already committed
    // (cursor included), so a transient DB error HERE must not flow into
    // the engine-failure path — that would re-queue (attempts 1-2) or
    // terminally fail (attempt 3) a day that succeeded. On failure the
    // row stays 'running'; the stale-running reaper reclaims it and the
    // retry simply continues from the already-advanced cursor.
    // errorMessage is cleared — a success must not keep displaying a
    // stale failure from an earlier attempt or reclaim.
    let completedPersisted = true;
    await prisma.driveSyncRun
      .update({
        where: { id: req.id },
        data: {
          status: 'completed',
          completedAt: new Date(),
          filesProcessed: result.filesProcessed,
          logSummary: tailLogSummary(captureLog),
          nextAttemptAt: null,
          errorMessage: null,
        },
      })
      .catch((updateErr) => {
        completedPersisted = false;
        console.error(
          JSON.stringify({
            msg: 'backfill-queue.completed.persist_error',
            requestId: req.id,
            error: updateErr instanceof Error ? updateErr.message : String(updateErr),
            hint: 'scan committed; row left running for the stale reaper — not an engine failure',
          }),
        );
      });
    console.log(
      JSON.stringify({
        msg: 'backfill-queue.completed',
        requestId: req.id,
        mode: req.mode,
        scansProcessed: result.scansProcessed,
        filesProcessed: result.filesProcessed,
        finalCursorYmd: result.finalCursorYmd,
        bootstrapCompleted: result.bootstrapCompleted,
        durationMs: result.durationMs,
      }),
    );

    // Self-trigger continuation: when this request was all_remaining
    // (bootstrap catchup chain) AND bootstrap is NOT done yet (more
    // active days remain). Each continuation produces ONE new 1-day
    // row that itself runs and re-queues if still behind. The chain
    // terminates naturally when the cursor catches up to today (then
    // bootstrapCompleted=true and we don't fire) OR when there are no
    // more active days (also bootstrapCompleted=true).
    //
    // Return continuationFired=true so the drain loop in
    // processBackfillQueue exits. Without this break, the same Job
    // would race the new Job for the continuation row we just wrote —
    // being already-warm, it would usually win the claim, leaving
    // the cold-started successor with nothing to do.
    let continuationFired = false;
    if (completedPersisted && req.allRemaining && !result.bootstrapCompleted) {
      const cont = await scheduleContinuation(req.id, req.accountId, req.mode);
      // Only a successfully TRIGGERED successor justifies breaking the
      // drain loop (racing it would starve the cold successor). On
      // 'trigger_failed' the pending row exists but no successor is
      // coming — keep draining so this warm process claims it. On
      // 'row_write_failed'/'misconfig' there is no successor row at all —
      // keep draining whatever else is queued.
      continuationFired = cont === 'triggered';
    }

    return { kind: 'completed', continuationFired };
  } catch (err) {
    const message = summarizeError(err);
    captureLog.push('', `[engine error attempt ${req.attempts}/${MAX_ATTEMPTS}] ${message}`);

    if (req.attempts >= MAX_ATTEMPTS) {
      // Terminal failure — operator resolves via UI.
      console.error(
        JSON.stringify({
          msg: 'backfill-queue.terminal_failure',
          requestId: req.id,
          attempts: req.attempts,
          error: message,
        }),
      );
      await prisma.driveSyncRun
        .update({
          where: { id: req.id },
          data: {
            status: 'failed',
            completedAt: new Date(),
            errorMessage: message,
            logSummary: tailLogSummary(captureLog),
            nextAttemptAt: null,
          },
        })
        .catch((updateErr) => {
          console.error(
            JSON.stringify({
              msg: 'backfill-queue.terminal_failure.persist_error',
              requestId: req.id,
              error: updateErr instanceof Error ? updateErr.message : String(updateErr),
            }),
          );
        });
      return { kind: 'failed' };
    }

    // Transient — re-queue with backoff.
    const nextAttemptAt = new Date(Date.now() + backoffMs(req.attempts));
    console.warn(
      JSON.stringify({
        msg: 'backfill-queue.retry_scheduled',
        requestId: req.id,
        attempts: req.attempts,
        nextAttemptAt: nextAttemptAt.toISOString(),
        error: message,
      }),
    );
    await prisma.driveSyncRun
      .update({
        where: { id: req.id },
        data: {
          status: 'pending',
          startedAt: null,
          errorMessage: message,
          logSummary: tailLogSummary(captureLog),
          nextAttemptAt,
        },
      })
      .catch((updateErr) => {
        console.error(
          JSON.stringify({
            msg: 'backfill-queue.retry_persist_error',
            requestId: req.id,
            error: updateErr instanceof Error ? updateErr.message : String(updateErr),
          }),
        );
      });
    return { kind: 'retried' };
  } finally {
    // Stop the heartbeat regardless of outcome (completed, retried,
    // terminal failure). Each processOne call owns its own ticker —
    // the drain loop may call processOne again on the next iteration
    // and that call sets up its own.
    clearInterval(heartbeat);
  }
}

/**
 * Single-invocation drain. Loops claim → process → claim … until either:
 *   - claimNext() returns null (queue empty or all eligible rows already
 *     claimed by a parallel execution, OR backoff-deferred)
 *   - MAX_REQUESTS_PER_INVOCATION is reached (runaway-safety backstop)
 *
 * Returns a structured summary so the Job's outcome log captures what
 * was done.
 */
export async function processBackfillQueue(): Promise<ProcessBackfillQueueResult> {
  const reclaimed = await reclaimStaleRunning();

  const summary: ProcessBackfillQueueResult = {
    reclaimed,
    processed: 0,
    completed: 0,
    failed: 0,
    retriedLater: 0,
    hitMaxRequests: false,
  };

  while (summary.processed < MAX_REQUESTS_PER_INVOCATION) {
    const claimed = await claimNext();
    if (!claimed) break;
    const outcome = await processOne(claimed);
    summary.processed += 1;
    if (outcome.kind === 'completed') summary.completed += 1;
    else if (outcome.kind === 'retried') summary.retriedLater += 1;
    else summary.failed += 1;

    // If this iteration triggered a continuation (all_remaining +
    // budget exhausted), STOP draining in this Job. A new Job was
    // just fired via Admin API and is supposed to own the next chunk.
    // Continuing the loop here would race the new Job: we'd usually
    // win because we're already warm, then process the continuation
    // chunk in a Job whose wall-clock budget is already gone, getting
    // SIGKILL'd at Cloud Run's task timeout with the row stuck in
    // 'running'. Exit cleanly here and let the new Job do its job.
    if (outcome.kind === 'completed' && outcome.continuationFired) {
      console.log(
        JSON.stringify({
          msg: 'backfill-queue.continuation-fired-exiting',
          parentRequestId: claimed.id,
          processedThisInvocation: summary.processed,
        }),
      );
      break;
    }
  }

  if (summary.processed === MAX_REQUESTS_PER_INVOCATION) {
    summary.hitMaxRequests = true;
  }

  return summary;
}
